library(dplyr)
library(shiny)
library(shinyjs)
library(shinyWidgets)
library(shinycssloaders)
library(shinycustomloader) 
library(bs4Dash)
library(fresh)
library(tippy)
library(DT)
library(flextable)
library(plotly)
library(stringr)
library(stringi)
library(echarts4r)
library(paletteer)


### loading all app dependencies into environment before they are going to be used in app 
### The name of the file within app dependencies is always the name of the variable loaded

total_number_of_PMIDs = readRDS("./data/total_number_PMIDs_per_disease.rds") %>% as.data.frame() # total_number_of_PMIDs per disease indication
parsed_tm = readRDS("./data/full_parsed_data.rds") # publications parsed by diseases
query_table = readRDS("./data/query_table.rds") %>% dplyr::select(query, `Number of Publications`)
pub_type = readRDS("./data/pub_type.rds")
year_choice = sort(unique(parsed_tm$year))
diseases = read.delim("./data/diseases_list.txt", encoding = "UTF-8")
tm.view = arrow::read_parquet("./data/pubmed_abstracts_mined_text2.parquet") 
tm.view$pmid = as.character(tm.view$pmid)
tm.view$year = as.character(tm.view$year)
genes_tm = arrow::read_parquet("./data/gene2pmids.parquet")
tm = tm.view %>% dplyr::select(pmid, year, title, abstract) %>% dplyr::distinct() # the metadata for the pmids (year, title & abstract)

# create a theme for the app
mytheme <- create_theme(
  bs4dash_vars(
    navbar_light_color = "#18BC9C",
    navbar_light_active_color = "#FFF",
    navbar_light_hover_color = "#FFF"
  ),
  bs4dash_yiq(
    contrasted_threshold = 10,
    text_dark = "#2C3E50", 
    text_light = "#FFF"
  ),
  bs4dash_layout(
    main_bg = "#FFF"
  ),
  bs4dash_sidebar_light(
    bg = "#2C3E50", 
    color = "#FFF",
    hover_color = "#18BC9C",
    submenu_bg = "#2C3E50", 
    submenu_color = "#18BC9C", 
    submenu_hover_color = "#18BC9C"
  ),
  bs4dash_status(
    primary = "#18BC9C", danger = "#E74C3C", light = "#18BC9C", success = '#18BC9C', info = '#3498DB', warning = '#F39C12'
  ),
  bs4dash_color(
    gray_900 = "#2C3E50", white = "#FFF"
  )
)

# to add color to the spinner 
options(spinner.color="#246479")

# the wrap_in() function
wrap_in <- function(.df, column, word, tag){
  class<-""
  if(grepl("\\.", tag)) {
    class <- sub(".+?\\.(.+)", " class='\\1'", tag)
    tag <- sub("\\..+", "", tag)
  }
  .df[[column]] <-  gsub(sprintf("(%s)", paste0(word, collapse="|")), sprintf("<%1$s%2$s>\\1</%1$s>", tag, class), .df[[column]], ignore.case = T)
  .df
}


# UI SIDE ####

## SIDEBAR #################################

sidebar <- bs4DashSidebar(skin = "light", 
                          bs4SidebarMenu(id = "sidebar", # id important for updateTabItems,
                                         menuItem("Introduction", tabName = "Intro", icon = icon("file-contract")),
                                         menuItem("Publications Metadata", tabName = "mined", icon = icon('monero')),
                                         menuItem("Frequency Plots", tabName = "freqplot", icon = icon("chart-bar")),
                                         menuItem("Publications", tabName = "pubmed", icon = icon("book-open")),
                                         menuItem("Gene Signature", tabName = "genesig", icon = icon("dna")),
                                         menuItem("Contact", tabName = "contact", icon = icon("address-card"))
                          ))

## BODY #################################


body <- dashboardBody(
  useShinyjs(), # Set up shinyjs
  fresh::use_theme(mytheme),
  setSliderColor(color = c('#F39C12', '#F39C12'), sliderId = c(1,2)),
  includeCSS('style.css'),
  tabItems(
    ### TAB 1: INTRODUCTION  #########################################
    tabItem("Intro",
            fluidPage(
              h2("Objective"),
              h4("Text mining can be used to search articles identifed with drug related queries and those articles
                 parsed for various indications(diseases) that may be of interest in drug treatment."),
              h2("Queries used in Text Mining"),
              h4("Below is a table of queries used to mine PubMed. Publications were downloaded from Pubmed in March-April 2022."),
              fluidRow(
                column(12,
                       DT::dataTableOutput("queries", width = "100%") %>% withSpinner(type = 6, size=2))
              ),
              h2("Diseases Parsed"),
              h4("Below is a table of the diseases/indications that were used to parse the publications generated by the queries."),
              fluidRow(
                column(12,
                       DT::dataTableOutput("disease_list", width = "100%") %>% withSpinner(type = 6, size=2))
              )
              
            )), # Intro tab
    
    ### TAB 2: PUBLICATIONS METADATA  #########################################
    tabItem("mined",
            fluidPage(
              h2("Summary of Publications"),
              h4("The publication's languages are summarized below. Publications written in the English language made up the majority of publications
                 so only these publications were parsed for the diseases/indications listed in the previous tab."),
              br(),
              fluidRow(
                column(4,
                       uiOutput('lang') %>% withSpinner(type = 6, size=1)),
                column(8,
                       echarts4rOutput("pie",  width = "100%", height = "700px") %>% withSpinner(type = 6, size=1)
                       )),
              br(),
              h4("The below graph summarizes the English language publications used to parse for the diseases/indications. They are displayed by choice of query(s) and summarized by year and publication type."),
              box(width = 12, title = "", collapsible = TRUE, collapsed = FALSE, status = "success", solidHeader = TRUE,
                  fluidRow(
                    column(4,
                           pickerInput(inputId = "query_picker", label = "Select Query(s)", choices = query_table$query, multiple = TRUE, options = list(`actions-box` = TRUE))),
                    column(4,
                           actionBttn(inputId = "plot_bar", label = "Plot", style = "unite", color = "royal"))),
                  br(),
                  fluidRow(
                    column(12,
                           echarts4rOutput("plot_1",  width = "100%", height = "900px")))
                  ),
              br(),
              h4("Below is a bar graph of the same publications but displayed by choice of publication type and ordered by number of publications in the query."),
              box(width = 12, title = "", collapsible = TRUE, collapsed = FALSE, status = "success", solidHeader = TRUE,
                  fluidRow(
                    column(4,
                           pickerInput(inputId = "pubtype", label = "Select Publication type(s)", choices = sort(pub_type$publicationtype[1:28]), multiple = TRUE, options = list(`actions-box` = TRUE))),
                    column(4, 
                           actionBttn(inputId = "plot_bar2", label = "Plot", style = "unite", color = "royal"))
                          ),
                  br(),
                  fluidRow(
                    column(12,
                           echarts4rOutput("plot_2",  width = "100%", height = "900px")))
                  ))
            ), # tab 2
    
    ### TAB 3: FREQUENCY PLOTS  #########################################
    tabItem("freqplot",
            fluidPage(
              h2("Frequency plot based on text mining output"),
              h5("- Select a query set to display a list of prioritized querys. Then choose one or several queries of interest as well as a range of years and press the button <Plot data>.
                            A ranked list of key disorders in the form of a barplot will appear. Key disorders are ranked based on their apperance/frequency in 
                            the titles/abstracts of the pooled publications selected by queries of interest."),
              h5("- The second plot represents the list of disorders ranked based on the NORMALIZED frequency. Normalization was done using total number of publications dedicated to the specific key disorder term.
                               Please, note that this plot is not updated if range of years other than the default (all years) is selected. "),
              h5("- Scroll down to see the interactive table with all frequency data. Click the indication in the 1st column to bring up the publications. "),
              br(),
              fluidRow(
                column(4,
                       pickerInput(inputId = "query_pick", label = "Select Query(s)", choices = query_table$query, options = list(`actions-box` = TRUE), multiple = TRUE))
              ),
              fluidRow(
                column(3,
                       sliderTextInput(inputId = "years", label = "Select a range of years:", choices = year_choice, selected = c(min(year_choice), max(year_choice)))),
                column(7,
                       checkboxGroupButtons("pubtypes", label = "Publication Type", choices = c("Journal Article", "Case Reports", "Clinical Trial", "Comparative Study", "Letter", "Comment", "Editorial"),
                                            size = 'sm',
                                            checkIcon = list(
                                              yes = tags$i(class = "fa fa-check-square", 
                                                           style = "color: #2C3E50"),
                                              no = tags$i(class = "fa fa-square-o", 
                                                          style = "color: #2C3E50")))),
                column(2,
                       actionBttn(inputId = "plot", label = "Plot Data", style = "float", color = "danger"))
              ),
              fluidRow(
                column(3,
                       valueBoxOutput("total_pubs", width = NULL)),
                column(4, 
                       valueBoxOutput("pubs_filtered", width = NULL))
              ),
              box(width = 12, title = HTML('<b style="color:white;">Frequency Plot</b>'), collapsible = TRUE, collapsed = FALSE, maximizable = T, status = "success", solidHeader = TRUE, background = "white",
                  label = boxLabel(text = "?", status = "danger") %>% tippy(tooltip = "Select a bar on the graph to display the publications.", interactive = TRUE, placement = "bottom"),
                  plotlyOutput("plot1", width = "100%", height = "800px") %>% withSpinner(type = 6, size=2) 
                  ),
              box(width = 12, title = HTML('<b style="color:white;">Normalized Frequency Plot</b>'), collapsible = TRUE, collapsed = FALSE, maximizable = T, status = "success", solidHeader = TRUE,
                  label = boxLabel(text = "?", status = "danger") %>% tippy(tooltip = "Select a bar on the graph to display the publications.", interactive = TRUE, placement = "bottom"),
                  plotlyOutput("plot2", width = "100%", height = "800px") %>% withSpinner(type = 6, size=2) 
                  ),
              box(width = 12, title = HTML('<b style="color:white;">Output Summary Table</b>'), collapsible = TRUE, collapsed = FALSE, status = "success", solidHeader = TRUE,
                  DT::dataTableOutput("tbl", width = "100%") %>% withSpinner(type = 6, size=2)
                  )

            )), # frequency tab
    ### TAB 4: PUBLICATIONS  #########################################
    tabItem("pubmed",
            fluidPage(
              h3("Publications"),
              h4("Select a disease/indication below to observe the publications from PubMed. You can also filter by year, by default all years are included."),
              fluidRow(
                column(6,
                       pickerInput("pick_disease", "Select Indication", choices = sort(unique(parsed_tm$diseases)), options = list(`live-search` = TRUE))),
                column(6,
                       sliderTextInput(inputId = "years2", label = "Select a range of years:", choices = year_choice, selected = c(min(year_choice), max(year_choice))))
              ),
              box(width = 12, title = HTML('<b style="color:white;">Publication Summary</b>'), collapsible = TRUE, collapsed = FALSE, status = "success", solidHeader = TRUE,
                  DT::dataTableOutput("tbl2", width = "100%") %>% withSpinner(type = 6, size=2)
              ))
            ), # publications tab
    
    ### TAB 5: GENE SIGNATURE  #########################################
    
    tabItem("genesig",
            fluidPage(
              h5("Select queries to generate a table of the most frequent genes within the publications."),
              h5("Additionally, you have the option to add a choice of disease indication to see the most frequent genes from the publications of the selected query but parsed by disease."),
              br(),
              fluidRow(
                column(3,
                       pickerInput(inputId = "query_pick2", label = "Select Query(ies)", choices = query_table$query, options = list(`actions-box` = TRUE), multiple = TRUE)),
                column(3, 
                       pickerInput("disease", "Optional parse by disease indication:", choices= "", multiple = TRUE, options = list(style = "btn-warning", `live-search` = TRUE, `actions-box` = TRUE))),
                column(2,
                       actionBttn(inputId = "button2", label = "Get Genes", style = "unite", color = "danger"))
              ),
              br(),
              br(),
              br(),
              fluidRow(
                column(12,
                       withLoader(DT::dataTableOutput("tbl3", width = "100%"), type="image", loader="coffee_gif.gif"))
              )
            )), # gene sig tab
    
    ### TAB CONTACT  #########################################
    tabItem("contact",
            fluidPage(
              h2("Developers"),
              "This app was developed by Desiree Williams",
              br(),
              h2("Contact information"),
              h5("E-mail: will.desi@gmail.com")
            )
    ) # tab contact
    
  )# tabItems
  
) #dashboardBody 


ui <- bs4DashPage(header = bs4DashNavbar(title = dashboardBrand(title = HTML('<b style="color:white;">Text Mining App</b>'), color = "primary"), skin = "light", status = ),
                  sidebar = sidebar,
                  body = body,
                  #footer = footer,
                  dark = NULL
)


# SERVER SIDE ####
server <- function(input, output, session) {

  
  ## TAB1: INTRODUCTION ##################

  output$queries <- DT::renderDataTable({
    DT::datatable(query_table, extensions = 'Buttons', filter = "top", escape = F, options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(10,20,-1), c(10,20,"All")), pageLength = 10), rownames = FALSE)
  })
  
  output$disease_list <- DT::renderDataTable({
    DT::datatable(diseases, extensions = 'Buttons', filter = "top", escape = F, options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(10,20,-1), c(10,20,"All")), pageLength = 10), rownames = FALSE)
  })
  
  
  ## TAB 2: PUBLICATION METADATA  #########################################
  
  language_table <- reactive({
    language_table = tm.view %>%
      dplyr::select(pmid, language) %>%
      dplyr::distinct() %>%
      count(language, sort = TRUE) %>%
      dplyr::mutate(Percentage = scales::percent(n/sum(n), accuracy = 0.1)) %>%
      bind_rows(summarise(., across(where(is.numeric), sum),
                          across(where(is.character), ~'Total'))) %>%
      dplyr::rename("Number of Publications" = "n")
    language_table[44,3] = '100%'
    language_table[40,1] = 'NA'
    language_table
  })
  
  output$lang <- renderUI({
    language_table() %>% flextable() %>% colformat_char(na_str = "NA") %>%
      footnote(i=10, j=1, value = as_paragraph(c("Undetermined")), ref_symbols = "1", part = "body", inline = TRUE) %>%
      autofit() %>% htmltools_value()
  })
  
  # plot pie chart using languages with more than 1500 publications so not to plot too many 0% languages
  pie_df <- reactive({
    language_table()[1:15,1:2] %>% dplyr::rename(name = language, value = "Number of Publications")
  })
  
  colors = c(paletteer_d("ggthemes::Superfishel_Stone"), '#BD582C', '#865640', '#9B8357', '#C2BC80', '#94A088')
  
  output$pie <- renderEcharts4r({
    pie_df() %>%
      e_charts(name) %>%
      e_pie(value) %>%
      e_color(colors) %>%
      e_tooltip(trigger = "item") %>%
      e_labels(show = TRUE, formatter = "{b} \n {d}%", position = "inside") %>%
      e_legend(left = 0, orient = 'vertical') %>%
      e_toolbox_feature("saveAsImage")
      
  })

  tm_view <- reactive({
    tm.view = tm.view %>% 
      dplyr::filter(language %in% 'eng') %>%
      dplyr::select(query, pmid, year, publicationtype) %>% dplyr::distinct() %>% collect()
  })
  
  plot <- eventReactive(input$plot_bar, {
    queries = stringi::stri_wrap(glue::glue_collapse(input$query_picker, sep = ", ", last = " and "), width = 90) 
    queries = stringi::stri_c(queries, collapse = "\n")
    pub_types = tm_view() %>% count(publicationtype, sort = T)
    pub_types = pub_types %>% filter(n >100) # show only publicationtype with more than 100 publications
    pub_types = pub_types$publicationtype
    plot_df = tm_view() %>% dplyr::filter(publicationtype %in% pub_types & query %in% input$query_picker) %>%
      count(year, publicationtype) %>%
      group_by(publicationtype)
    plot = plot_df %>%
      e_charts(year, stack = "grp") %>%
      e_bar(n) %>%
      e_color(my_colors) %>%
      e_grid(bottom = '20%', top = '15%') %>%
      #e_legend(orient = 'vertical', 
      #         right = '10', top = '15%') %>%
      e_legend(bottom = 0) %>% # move legend to the bottom
      e_tooltip(trigger = "item") %>%
      e_x_axis(axisLabel = list(interval = 0, rotate = 90)) %>%
      e_axis_labels(x = "Year", y = "Number of Publications") %>%
      e_title(text = "Publications for the selected queries:", 
              subtext = queries, left = "center") %>%
      e_toolbox_feature("saveAsImage")
    plot
  })
  
  my_colors <- c("#4E79A7FF","#A0CBE8FF","#F28E2BFF","#FFBE7DFF","#59A14FFF","#8CD17DFF","#B6992DFF","#F1CE63FF","#499894FF","#86BCB6FF","#E15759FF","#FF9D9AFF","#79706EFF","#BAB0ACFF","#D37295FF","#FABFD2FF","#B07AA1FF","#D4A6C8FF","#9D7660FF","#D7B5A6FF","#BD582C", "#E48312","#000000","#D7CE9F")
  
  output$plot_1 <- renderEcharts4r({
    plot() 
  })
  
  color2 = paletteer_d("Polychrome::kelly")
  colors2 = rev(color2)
  
  plot2 <- eventReactive(input$plot_bar2, {
    pubs = stringi::stri_wrap(glue::glue_collapse(input$pubtype, sep = ", ", last = " and "), width = 90) 
    pubs = stringi::stri_c(pubs, collapse = "\n")
    plot_df = tm_view() %>% filter(publicationtype %in% input$pubtype) %>%
      count(year, query) %>%
      group_by(query)

    plot = plot_df %>%
      e_charts(year, stack = "grp") %>%
      e_bar(n) %>%
      e_color(colors2) %>%
      e_grid(bottom = '45%', top = '15%') %>%
      #e_legend(orient = 'vertical', 
      #         right = '10', top = '15%') %>%
      e_legend(bottom = 0) %>% # move legend to the bottom
      e_tooltip(trigger = "item") %>%
      e_x_axis(axisLabel = list(interval = 0, rotate = 90)) %>%
      e_axis_labels(x = "Year", y = "Number of Publications") %>%
      e_title(text = "Publications for the selected Publication Types:", 
              subtext = pubs, left = "center") %>%
      e_toolbox_feature("saveAsImage")
    plot
  })
  
  output$plot_2 <- renderEcharts4r({
    plot2() 
  })

  
  ## TAB 3: FREQUENCY PLOTS  #########################################
  
  tm_filt <- eventReactive(input$plot, {
    tm_full <- parsed_tm %>%
      dplyr::filter(query %in% input$query_pick) %>%
      dplyr::filter(year <= input$years[2] & year >= input$years[1])
    if(!is.null(input$pubtypes)){
      tm_full <- tm_full %>% dplyr::filter(grepl(paste(input$pubtypes, sep = "|"), publicationtype, ignore.case = T))
    }
    tm_full = tm_full %>% dplyr::select(disease_in_title, pmid, year, diseases, disease_in_abstract) %>%
      dplyr::distinct(diseases, pmid, year, .keep_all = T)
    tm_full
  })
  
  output$total_pubs <- renderValueBox({
    tm_eng = tm.view %>% dplyr::filter(language %in% "eng") %>% dplyr::select(pmid) %>% dplyr::distinct()
    valueBox(value = scales::comma(length(unique(tm_eng$pmid))), subtitle = "Total number of unique publications", color = "info", icon =icon("record", lib = "glyphicon"))
  })
  
  output$pubs_filtered <- renderValueBox({
    valueBox(value = scales::comma(length(unique(tm_filt()$pmid))), subtitle = "Total number of unique publications in query(s) & selections", color = "info", icon =icon("record", lib = "glyphicon"))
  })

  textdata <- eventReactive(input$plot, {
    if(dim(tm_filt())[1] != 0){
      df_p = tm_filt() %>% count(diseases, disease_in_title) %>% na.omit()
      df_p_f = aggregate(n ~diseases, df_p, sum) %>% dplyr::rename(Title = n)                
      df_abs = tm_filt() %>% count(diseases, disease_in_abstract) %>% na.omit()
      df_abs_f = aggregate(n ~diseases, df_abs, sum) %>% dplyr::rename(Abstract = n) 
      df_final = full_join(df_p_f, df_abs_f, by = "diseases") %>% dplyr::rename(Disease = diseases)
      df_3 = left_join(df_final, total_number_of_PMIDs, by = "Disease") %>%
        mutate(ratio.title = Title*1000/Total_number_of_PMIDs, ratio.abst = Abstract*1000/Total_number_of_PMIDs) %>% mutate(across(starts_with("ratio"), round, 3))
      df_3[is.na(df_3)] <- 0
      df_3 = df_3 %>% arrange(desc(Abstract))
      df_3
    } else{
      validate("One or more filtering conditions don't exist. Change parameters and replot data.")
    }
    
  })
  
  # generate an error if returns nothing
  observeEvent(input$plot, {
    if (dim(tm_filt())[1] == 0){
      shinyalert("Oops!", "One or more filtering conditions don't exist. Adjust filtering parameters and replot data.", type = "error")
    }
  })
  
  total_pubs <- reactive({
    total_pubs = tm_filt() %>% dplyr::distinct(diseases, pmid, year) 
    total_pubs = scales::comma(dim(total_pubs)[1])
    total_pubs
  })

  textminingplot <- eventReactive(input$plot,{
    queries = stringi::stri_wrap(glue::glue_collapse(input$query_pick, sep = ", ", last = " and "), width = 90) 
    queries = stringi::stri_c(queries, collapse = "\n")
    title = paste0("Raw text-mining output from ", input$years[1], " to ", input$years[2], '<br>','<sup>', "English publications only",'</sup>')
    anno = paste0("Displaying the top 30 indications from a total of ", total_pubs(), " publications in selected queries: ", queries)
    textdata.df <- textdata()[1:30,]
    textdata.df$Disease = factor(textdata.df$Disease, levels = unique(textdata.df$Disease)[order(textdata.df$Abstract, decreasing = FALSE)])
    plot <- textdata.df %>% plot_ly(source = 'pubs') %>%
      add_trace(name = "Abstract", type = "bar", orientation = "h", x = ~Abstract, y= ~Disease, hovertext = paste("Disorder: ", textdata.df$Disease, "\n", "Frequency in Abstracts: ", textdata.df$Abstract, "\n", "Total number of PMIDs for this indication: ", textdata.df$Total_number_of_PMIDs), hoverinfo="text", marker = list(color = '#7c3a62', line = list(color = '#50263F', width = 2))) %>%
      add_trace(name = "Title", type = "bar", orientation = "h", x = ~Title, y= ~Disease, hovertext = paste("Disorder: ", textdata.df$Disease, "\n", "Frequency in Titles: ", textdata.df$Title, "\n", "Total number of PMIDs for this indication: ", textdata.df$Total_number_of_PMIDs), hoverinfo="text", marker = list(color = '#8A87A6', line = list(color = '#45435A', width = 2))) %>%
      layout(barmode = "stack", title=list(text = title, x = 0 , y = 1.5), xaxis = list(title = "Number of publications"), yaxis = list(title = "", dtick=0.75, tick0=0.5, tickmode="linear"),
             margin = list(l = 25, r = 25, t = 60, b = 200),
             annotations = list(text = anno, showarrow = F,
                                xref='paper', x = -0.2, yref='paper', y = -0.3, 
                                font=list(size=10, color="#f29e4c"))
             ) %>% 
      config(toImageButtonOptions = list(format = "png", width = 1500, height = 800))
    plot %>% event_register("plotly_click")
  })
  
  output$plot1 <- renderPlotly({
    textminingplot()
  })
  
  observeEvent(event_data("plotly_click", source = "pubs"),
               {
                 event_data = event_data("plotly_click", source = "pubs")
                 showModal(modalDialog(
                   DT::renderDataTable({
                     tm_full <- parsed_tm %>%
                       dplyr::filter(query %in% input$query_pick) %>%
                       dplyr::filter(year <= input$years[2] & year >= input$years[1])
                     if(!is.null(input$pubtypes)){
                       tm_full <- tm_full %>% dplyr::filter(grepl(paste(input$pubtypes, sep = "|"), publicationtype, ignore.case = T))
                     }
                     tm_full = tm_full %>% dplyr::distinct(diseases, pmid, year, publicationtype) %>% 
                       dplyr::rename(PMID=pmid, Year=year, Indication=diseases, `Publication Type` = publicationtype)
                     tm_full = tm_full %>% left_join(tm, by = c("PMID" = 'pmid', 'Year'= 'year')) %>% dplyr::distinct(Indication, PMID, Year, .keep_all = T) %>% dplyr::select(Indication, PMID, Year, title, abstract, `Publication Type`)
                     df_subset = tm_full %>% dplyr::filter(Indication %in% event_data$y)
                     df_subset$PMID = paste0("<a href='","https://pubmed.ncbi.nlm.nih.gov/", df_subset$PMID, "' target='_blank'>", df_subset$PMID, "</a>")
                     word = unique(df_subset$Indication)
                     dt = df_subset %>% wrap_in( "abstract",  word, "mark") %>% wrap_in( "title",  word, "mark") %>%
                       DT::datatable(extensions = 'Buttons', filter = "top", escape = F, options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(4,10,20,-1), c(4,10,20,"All")), pageLength = 4), rownames = FALSE)
                     dt
                   }),
                   size = "l", 
                   footer = modalButton("Close")
                 ))
               })
  
  textDataNormalized <- eventReactive(input$plot, {
    if(dim(tm_filt())[1] != 0){
      tm_full <- parsed_tm %>%
        dplyr::filter(query %in% input$query_pick)
      if(!is.null(input$pubtypes)){
        tm_full <- tm_full %>% dplyr::filter(grepl(paste(input$pubtypes, sep = "|"), publicationtype, ignore.case = T))
      }
      tm_full = tm_full %>% dplyr::select(disease_in_title, pmid, year, diseases, disease_in_abstract) %>%
        dplyr::distinct(diseases, pmid, year, .keep_all = T)
      df_p = tm_full %>% count(diseases, disease_in_title) %>% na.omit()
      df_p_f = aggregate(n ~diseases, df_p, sum) %>% dplyr::rename(Title = n)                
      df_abs = tm_full %>% count(diseases, disease_in_abstract) %>% na.omit()
      df_abs_f = aggregate(n ~diseases, df_abs, sum) %>% dplyr::rename(Abstract = n) 
      df_final = full_join(df_p_f, df_abs_f, by = "diseases") %>% dplyr::rename(Disease = diseases)
      df_3 = left_join(df_final, total_number_of_PMIDs, by = "Disease") %>%
        mutate(ratio.abst = Abstract*1000/Total_number_of_PMIDs, ratio.title = Title*1000/Total_number_of_PMIDs) %>% mutate(across(starts_with("ratio"), round, 3))
      df_3[is.na(df_3)] <- 0
      df_3 = df_3 %>% arrange(desc(ratio.abst))
      df_3
    } else{
      validate("One or more filtering conditions don't exist. Change parameters and replot data.")
    }
  })
  
  total_pubs_n <- reactive({
    tm_full <- parsed_tm %>%
      dplyr::filter(query %in% input$query_pick)
    if(!is.null(input$pubtypes)){
      tm_full <- tm_full %>% dplyr::filter(grepl(paste(input$pubtypes, sep = "|"), publicationtype, ignore.case = T))
    }
    tm_full = tm_full %>% dplyr::select(disease_in_title, pmid, year, diseases, disease_in_abstract) %>%
      dplyr::distinct(diseases, pmid, year, .keep_all = T)
    total_pubs = tm_full %>% dplyr::distinct(diseases, pmid, year) 
    total_pubs = scales::comma(dim(total_pubs)[1])
    total_pubs
  })
  
  plotnormalized <- eventReactive(input$plot,{
    queries = stringi::stri_wrap(glue::glue_collapse(input$query_pick, sep = ", ", last = " and "), width = 90) 
    queries = stringi::stri_c(queries, collapse = "\n")
    title = paste0("Normalized text-mining output from 1942 to 2022", '<br>','<sup>', "English publications only",'</sup>')
    anno = paste0("Displaying the top 30 indications from a total of ", total_pubs_n(), " publications in selected queries: ", queries)
    textdata.df <- textDataNormalized()[1:30,]
    textdata.df$Disease = factor(textdata.df$Disease, levels = unique(textdata.df$Disease)[order(textdata.df$ratio.abst, decreasing = FALSE)])
    plot <- textdata.df %>% plot_ly(source = 'pubs2') %>%
      add_trace(name = "Abstract", type = "bar", orientation = "h", x = ~ratio.abst, y= ~Disease, hovertext = paste("Disorder: ", textdata.df$Disease, "\n", "Frequency in Abstracts: ", textdata.df$Abstract, "\n", "Total number of PMIDs for this indication: ", textdata.df$Total_number_of_PMIDs), hoverinfo="text", marker = list(color = '#246479', line = list(color = '#1A4857', width = 2))) %>%
      add_trace(name = "Title", type = "bar", orientation = "h", x = ~ratio.title, y= ~Disease, hovertext = paste("Disorder: ", textdata.df$Disease, "\n", "Frequency in Titles: ", textdata.df$Title, "\n", "Total number of PMIDs for this indication: ", textdata.df$Total_number_of_PMIDs), hoverinfo="text", marker = list(color = '#7680A0', line = list(color = '#464D65', width = 2))) %>%
      layout(barmode = "stack", title=list(text = title, x = 0 , y = 1.5), xaxis = list(title = "[Number of publications *1,000]/total number of publications"), yaxis = list(title = "", dtick=0.75, tick0=0.5, tickmode="linear"),
             margin = list(l = 25, r = 25, t = 60, b = 200),
             annotations = list(text = anno, showarrow = F,
                                xref='paper', x = -0.2, yref='paper', y = -0.3, 
                                xanchor = 'left', yanchor ='bottom',
                                font=list(size=10, color="#f29e4c"))
             ) %>% 
      config(toImageButtonOptions = list(format = "png", width = 1500, height = 800))
    plot %>% event_register("plotly_click")
  })
  
  output$plot2 <- renderPlotly({
    plotnormalized()
  })
  
  observeEvent(event_data("plotly_click", source = "pubs2"),
               {
                 event_data = event_data("plotly_click", source = "pubs2")
                 showModal(modalDialog(
                   DT::renderDataTable({
                     tm_full <- parsed_tm %>% dplyr::filter(query %in% input$query_pick)
                     if(!is.null(input$pubtypes)){
                       tm_full <- tm_full %>% dplyr::filter(grepl(paste(input$pubtypes, sep = "|"), publicationtype, ignore.case = T))
                     }
                     tm_full = tm_full %>% dplyr::distinct(diseases, pmid, year, publicationtype) %>% 
                       dplyr::rename(PMID=pmid, Year=year, Indication=diseases, `Publication Type` = publicationtype)
                     tm_full = tm_full %>% left_join(tm, by = c("PMID" = 'pmid', 'Year'= 'year')) %>% dplyr::distinct(Indication, PMID, Year, .keep_all = T) %>% dplyr::select(Indication, PMID, Year, title, abstract, `Publication Type`)
                     df_subset = tm_full %>% dplyr::filter(Indication %in% event_data$y)
                     df_subset$PMID = paste0("<a href='","https://pubmed.ncbi.nlm.nih.gov/", df_subset$PMID, "' target='_blank'>", df_subset$PMID, "</a>")
                     word = unique(df_subset$Indication)
                     dt = df_subset %>% wrap_in( "abstract",  word, "mark") %>% wrap_in( "title",  word, "mark") %>%
                       DT::datatable(extensions = 'Buttons', filter = "top", escape = F, options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(4,10,20,-1), c(4,10,20,"All")), pageLength = 4), rownames = FALSE)
                     dt
                   }),
                   size = "l", 
                   footer = modalButton("Close")
                 ))
               })
  
  output$tbl <- renderDT({
    textdata() %>% dplyr::rename(Raw_count_in_titles = Title, Raw_count_in_abstracts = Abstract, Normalized_count_in_abstracts = ratio.abst, Normalized_count_in_titles = ratio.title) %>%
      dplyr::mutate(Disease = paste0("<button class='table_btn' title='Click to see publications'>", Disease, "</button>")) %>% 
      DT::datatable(extensions = 'Buttons', filter = "top", escape = F, selection = "none", class = 'cell-border strip hover', options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(10,20,-1), c(10,20,"All")), pageLength = 10), rownames = FALSE) %>% formatStyle(0, cursor = 'pointer')
  })
  
  observeEvent(input$tbl_cell_clicked,{
    info = input$tbl_cell_clicked
    # do nothing if not clicked yet, or the clicked cell is not in the 1st column
    if (is.null(info$value) || info$col != 0) return()
    showModal(modalDialog(
      DT::renderDataTable({
        tm_full <- parsed_tm %>%
          dplyr::filter(query %in% input$query_pick) %>%
          dplyr::filter(year <= input$years[2] & year >= input$years[1])
        if(!is.null(input$pubtypes)){
          tm_full <- tm_full %>% dplyr::filter(grepl(paste(input$pubtypes, sep = "|"), publicationtype, ignore.case = T))
        }
        tm_full = tm_full %>% dplyr::distinct(diseases, pmid, year, publicationtype) #%>% dplyr::rename(PMID=pmid, Year=year, Indication=diseases, `Publication Type` = publicationtype)
        tm_full = tm_full %>% left_join(tm, by = c('pmid', 'year')) %>% dplyr::select(diseases, pmid, year, title, abstract, publicationtype) %>% dplyr::distinct(diseases, pmid, year, .keep_all = T) 
        v1_value <- gsub("<.*?>", "", info$value)
        tm_full = tm_full %>% dplyr::filter(diseases %in% v1_value)
        tm_full$pmid = paste0("<a href='","https://pubmed.ncbi.nlm.nih.gov/", tm_full$pmid, "' target='_blank'>", tm_full$pmid, "</a>")
        word = unique(tm_full$diseases)
        dt = tm_full %>% wrap_in( "abstract",  word, "mark") %>% wrap_in( "title",  word, "mark") %>%
          DT::datatable(extensions = 'Buttons', filter = "top", escape = F, options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(4,10,20,-1), c(4,10,20,"All")), pageLength = 4), rownames = FALSE)
        dt
      }),
    size = "l", footer = modalButton("Close")))
  })


  ## TAB 4: PUBLICATIONS  #########################################
  
  
  pubdata <- reactive({
    df = parsed_tm %>% dplyr::filter(diseases %in% input$pick_disease) %>% dplyr::filter(year <= input$years2[2] & year >= input$years2[1]) %>%
      dplyr::select(pmid, year, disease_in_title, disease_in_abstract, query, publicationtype) %>% dplyr::distinct() %>%
      dplyr::rename(PMID = pmid, Year=year, Query=query, `Publication Type` =publicationtype) %>%
      left_join(tm, by = c("PMID" = 'pmid', 'Year'= 'year'))
    df$PMID = paste0("<a href='","https://pubmed.ncbi.nlm.nih.gov/", df$PMID, "' target='_blank'>", df$PMID, "</a>")
    df
  })
  
  output$tbl2 <- renderDT({
    df = pubdata()
    word_T = unique(df$disease_in_title) %>% na.omit()
    word_A = unique(df$disease_in_abstract) %>% na.omit()
    dt = df %>% dplyr::select(Query, PMID, Year, title, abstract, `Publication Type`) %>%
      dplyr::distinct(PMID, Year, Query, .keep_all = TRUE) %>%
      wrap_in( "abstract",  word_A, "mark") %>% wrap_in( "title",  word_T, "mark") %>%
      DT::datatable(extensions = 'Buttons', filter = "top", escape = F, selection = "none", class = 'cell-border strip hover', options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(4,10,20,-1), c(4,10,20,"All")), pageLength = 4), rownames = FALSE)
    dt
  })
  
  ## TAB 5: GENE SIGNATURE  #########################################

  # provide choice of disease where there are more than 3 publications containing the parsed indication within abstracts
  observe({
    df = parsed_tm %>% filter(query %in% input$query_pick2) %>% dplyr::distinct(pmid, year, diseases, disease_in_abstract)
    df2 = df %>% count(diseases, disease_in_abstract, sort = T) %>% na.omit() %>% dplyr::filter(n >=3)
    dList = df2$diseases
    updatePickerInput(session, "disease", choices = dList)
  })

  gene_list <- eventReactive(input$button2, {
    if(is.null(input$disease)){
      df3 = parsed_tm %>% filter(query %in% input$query_pick2) %>% dplyr::distinct(pmid, year, query) 
    } else {
      df3 = parsed_tm %>% filter(query %in% input$query_pick2 & diseases %in% input$disease) %>% dplyr::distinct(pmid, year, diseases, query) 
    }
    df4 = df3 %>% dplyr::left_join(genes_tm, by = "pmid") %>% tidyr::drop_na(symbol) %>% dplyr::distinct(pmid, year, symbol, geneid, .keep_all = T)
    df5 = df4 %>% dplyr::count(symbol, geneid, synonyms, description, sort=TRUE) %>% dplyr::rename("Gene Synonym" = synonyms, Description = description, "Number in publications" = n)
    df5
  })
  
  output$tbl3 <- DT::renderDataTable({
    gene_list() %>% dplyr::mutate(symbol = paste0("<button class='table_btn' title='Click to see publications'>", symbol, "</button>")) %>%
      DT::datatable(extensions = 'Buttons', filter = "top", escape = F, selection = "none", class = 'cell-border strip hover', options = list( "dom" = 'T<"clear">lBfrtip', buttons = list('copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(10,20,-1), c(10,20,"All")), pageLength = 10), rownames = FALSE) %>% formatStyle(0, cursor = 'pointer')
  })
  
  observeEvent(input$tbl3_cell_clicked, {
    info = input$tbl3_cell_clicked
    # do nothing if not clicked yet, or the clicked cell is not in the 1st column
    if (is.null(info$value) || info$col != 0) return()
    showModal(modalDialog(
      DT::renderDataTable({
        if (is.null(input$disease)){
          df = parsed_tm %>% filter(query %in% input$query_pick2) %>% dplyr::distinct(pmid, year, query) 
          df_genes = df %>% dplyr::left_join(genes_tm, by = "pmid") %>% tidyr::drop_na(symbol) %>% 
            left_join(tm, by = c("pmid", "year")) %>% dplyr::distinct(pmid, year, symbol, geneid, .keep_all = T)
          df_genes = df_genes %>% dplyr::group_by(pmid, year, symbol, geneid, synonyms, description, title, abstract) %>% summarize(query = stringr::str_c(query, collapse = ", ")) %>% dplyr::ungroup()
        } else {
          df_alt = parsed_tm %>% filter(query %in% input$query_pick2 & diseases %in% input$disease) %>% dplyr::distinct(pmid, year, diseases, query) 
          df_genes = df_alt %>% dplyr::left_join(genes_tm, by = "pmid") %>% tidyr::drop_na(symbol) %>% 
            left_join(tm, by = c("pmid", "year")) %>% dplyr::distinct(pmid, year, symbol, geneid, diseases, query, .keep_all = T)
          df_genes = df_genes %>% dplyr::group_by(pmid, year, symbol, geneid, synonyms, description, title, abstract) %>% summarize(diseases = stringr::str_c(diseases, collapse = ", "), query = stringr::str_c(query, collapse = ", ")) %>% dplyr::ungroup()
          df_genes$diseases = sapply(df_genes$diseases, function(x) paste(unique(unlist(str_split(x,", "))), collapse = ", "))
        }
        df_genes$query = sapply(df_genes$query, function(x) paste(unique(unlist(str_split(x,", "))), collapse = ", "))
        v1_value <- gsub("<.*?>", "", info$value)
        df_genes = df_genes %>% dplyr::filter(symbol %in% v1_value)
        df_genes$pmid = paste0("<a href='","https://pubmed.ncbi.nlm.nih.gov/", df_genes$pmid, "' target='_blank'>", df_genes$pmid, "</a>")
        word = unique(df_genes$symbol)
        dt = df_genes %>% wrap_in2("abstract",  word, "mark") %>%
          DT::datatable(extensions = c('Buttons', 'Responsive'), filter = "top", escape = F, selection = "none", options = list(dom='Bflrtip', buttons = list('colvis', 'copy', list(extend = "collection", buttons = c("csv", "excel", "pdf"), text = "Download")), lengthMenu = list(c(4,10,20,-1), c(4,10,20,"All")), pageLength = 4), rownames = FALSE)
        dt
      }),
      size = "l", 
      footer = modalButton("Close")))
  })


  wrap_in2 <- function(.df, column, word, tag){
    class<-""
    if(grepl("\\.", tag)) {
      class <- sub(".+?\\.(.+)", " class='\\1'", tag)
      tag <- sub("\\..+", "", tag)
    }
    .df[[column]] <-  gsub(sprintf("(%s)", paste0(word, collapse="|")), sprintf("<%1$s%2$s>\\1</%1$s>", tag, class), .df[[column]], ignore.case = F)
    .df
  }
  


} # server

shinyApp(ui, server)
